---
- name: verify that required parameters are set for drone agent setup
  fail: msg="Variable '{{ item }}' is not defined for drone agent setup"
  when: item not in vars
  with_items:
     - drone_server_host
  tags: [configuration]

- name: add config folder for drone-agent
  file:
    path: "/etc/drone/agent"
    state: "directory"

- name: copy config for drone agent
  template:
    src: "drone-agent.config.j2"
    dest: "/etc/drone/agent/drone-agent.config"
  register: drone_agent_config
  tags: [configuration]

- name: create docker-compose file for agent
  template:
    src: "drone-agent-compose.yml.j2"
    dest: "/etc/drone/agent/docker-compose.yml"
  register: drone_agent_compose

- name: stop agent instace(s)
  docker_service:
    project_src: /etc/drone/agent
    state: absent
  when: (drone_agent_compose is defined and drone_agent_compose.changed) or (drone_agent_config is defined and drone_agent_config.changed)
  tags: [configuration]

- name: start agent instance(s)
  docker_service:
    project_src: /etc/drone/agent
    state: present
    build: no
  tags: [configuration]

- name: scale agents
  docker_service:
    project_src: /etc/drone/agent
    scale:
      drone-agent: "{{ drone_agent_count }}"
  when: drone_agent_count != 1
  tags: [configuration]
